### ISSUE TITLE
WMCP Migration to github

### ISSUE THREAD

**Issue by efucile** [wmo-im/wmcp#1]
- Schema, Code Tables import in github (csv, ttl (skos) for a provision in codes.wmo.int ?) and governance
- Add documentation (wiki page) as necessary (for the XSD schema, ...) ?
- WMCP Wiki (including Specification) Migration ?
- Guidance + documentation migration ?

**Comment by hermannasensio** [comment]
migration content from http://wis.wmo.int/ ?

**Comment by hermannasensio** [comment]
first put template with example of wmo core metatdata profile 1.3 and the validationTestSuite wich contains a schematron and a short Readme, from the wiswiki and http://wis.wmo.int/2012/metadata/validationTestSuite/

**Comment by hermannasensio** [comment]
https://github.com/OGCMetOceanDWG/wmo-cmp-ts
is a testsuite in Python for WMO Core Metadata Profile by Tom Kralidis

**Comment by gaubert** [comment]
@hermannasensio any experience with the test suite built by Tom Kralidis ?

**Comment by gaubert** [comment]
I have a create a csv file from [(https://github.com/wmo-im/wmcp/blob/master/codelists/WMOCodeLists.xml)]
It is browsable and available here: [WMO_DataLicenseCode.csv]
The same can be done for the rest of the code tables in WMOCodeLists.xml. Still to be done are WMO_GTSProductCategoryCode, WMO_CategoryCode, WMO_DistributionScopeCode,

**Comment by hermannasensio** [comment]
@gaubert : personally I have not worked with the Python Test Suite from Tom Kralidis - but this Test Suite is mentioned in the WisWiki https://wiswiki.wmo.int/tiki-index.php?page=MDG_Test
@all: has anyone experience with this Test Suite?

**Comment by Manuel-Fuentes** [comment]
We have a question: will the schemas and code lists be maintained form github ? At present, many XML records deployed in WIS are validating against schemas published in wis.wmo.int. Will we need to update all records ?

**Comment by gaubert** [comment]
@Manuel-Fuentes good point on a metadata record, I see the schema available from here: http://wis.wmo.int/2011/schemata/iso19139_2007/schema/gmd/gmd.xsd" 

Can we do the same thing in github ? We need a strategy or organisation to do that ?
What is Enrico's (WMO) view. Does WMO wants to publish the schemas under its domain name ?

**Comment by efucile** [comment]
GitHub is the development repository. Deployment of final releases of the schemas will still be in wis.wmo.int. I think that we need to prepare to a better release process with a good version system where we develop a schema version in github, we make a release on github and we deploy in wis.wmo.int. At the moment we have a very unclean situation on wis.wmo.int with directories with dates. I would prefer to have versions.
