### ISSUE TITLE
KPIs Definition

### ISSUE THREAD

**Issue by gaubert** [wmo-im/wmcp#14]
Please post a message here once you have updated your assigned KPI.
Please feel free to add additional KPIs.

**Comment by hermannasensio** [comment]
Hi,
the point F) Link for WMOEssential data 
is updated, including an example

**Comment by gaubert** [comment]
Thanks Hermann, as you said during the Telco F) is also touching on the broken links issue.

**Comment by amilan17** [comment]
Updated B and C.
