### ISSUE TITLE
report face to face meeting 2019

### ISSUE THREAD

**Issue by efucile** [wmo-im/wmcp#50]
Draft final report of the meeting

**Comment by efucile** [comment]
Here is the draft final report https://wmoomm-my.sharepoint.com/:w:/r/personal/efucile_wmo_int/Documents/Teams/TT-WISMD/TT-WISMD-final-report.docx?d=w4646100c690f42889fff868bba0ff93e&csf=1&e=iBvV0p

@wmo-im/tt-wismd please review and let me know.

**Comment by martaguti** [comment]
Enrico 
I cannot access the link  I get an error 

If that doesn't help, contact your support team and include these technical details:
Correlation ID: 1218209f-40e9-2000-4070-8ba550d1259a
Date and Time: 12/10/2019 2:21:52 AM
URL: https://wmoomm-my.sharepoint.com/personal/efucile_wmo_int/Documents/Teams/TT-WISMD/TT-WISMD-final-report.docx?d=w4646100c690f42889fff868bba0ff93e&csf=1&e=iBvV0p&cid=9a3c7287-7d65-4aa8-83d8-adcdff592109
User: Marta.Gutierrez@ecmwf.int
Issue Type: User not in directory.

**Comment by gaubert** [comment]
Same for me we need to login to access the file. Is there a way to access the document without having to login ?

**Comment by tomkralidis** [comment]
I cannot access this file either. @efucile please advise?  Also, how should we review/address/approve these minutes given the time that has since passed, and the recent formation of the new TT-WISMD?

**Comment by efucile** [comment]
report is available from meeting page [old wiswiki page](https://old.wmo.int/wiswiki/tiki-index.php%3Fpage=TT-WIS-MD-1.html)
