### ISSUE TITLE
teleconference 23.1.2020

### ISSUE THREAD

**Issue by efucile** [wmo-im/wmcp#52]
Hello @wmo-im/tt-wismd 
we are going to have a teleconference on Thursday to review the progress on KPIs. Please have a look at the KPI assigned to yourself.
These are info for the blueJeans teleconference.

Meeting URL
https://bluejeans.com/497597571?src=join_info

Meeting ID
497 597 571

Want to dial in from a phone?

Dial one of the following numbers:
+1.408.740.7256 (US (San Jose))
+1.888.240.2560 (US Toll Free)
(see all numbers - https://www.bluejeans.com/premium-numbers)

Enter the meeting ID and passcode followed by #

Connecting from a room system?
Dial: bjn.vc or 199.48.152.152 and enter your meeting ID & passcode

**Comment by martaguti** [comment]
Hi @efucile ,
Telco on Thursday, right?

**Comment by efucile** [comment]
yes telco Thursday, January 23 2:00 – 3:00pm GMT

**Comment by tomkralidis** [comment]
To confirm: https://www.timeanddate.com/worldclock/meetingdetails.html?year=2020&month=1&day=23&hour=14&min=0&sec=0&p1=250&p2=87&p3=137&p4=152

**Comment by efucile** [comment]
@tomkralidis correct
